import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to silly-mantis-bob-17572d58317047</h1>
        <p>This app was generated by Applaa</p>
      </header>
    </div>
  );
}

export default App;